version: "2"

services:
    service-a:
        build: ./service-a
        ports:
            - "8080:80"
        depends_on:
            - service-b
            - mycache
            
    service-b:
        build: ./service-b
        expose:
            - "80"

    mycache:
        image: redis:alpine
